# Generated by Django 5.0.1 on 2025-10-22 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_teacherprofile_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='relevant_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.course'),
        ),
        migrations.AddField(
            model_name='notification',
            name='relevant_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('session_started', 'Session Started'), ('attendance_marked', 'Attendance Marked'), ('late_warning', 'Late Warning'), ('absent_alert', 'Absent Alert'), ('badge_earned', 'Badge Earned'), ('session_summary', 'Session Summary'), ('unusual_attendance', 'Unusual Attendance'), ('student_milestone', 'Student Milestone'), ('absence_pattern', 'Absence Pattern')], max_length=20),
        ),
    ]
